### ISSUE TITLE
ModuleNotFoundError: No module named 'data.load_data'

### ISSUE THREAD

**Issue by Dylan-Dyb** [LongxingTan/Time-series-prediction#8]

**Comment by pnmartinez** [comment]
Have a similar problem that has to do with **routing too** (though it is not described in the issue, I assume my problem is similar; check the logs below).

When running
```
!python run_train.py --use_model seq2seq
```
I get:

```
Traceback (most recent call last):
  File "run_train.py", line 10, in <module>
    from data.load_data import DataLoader
  File "/content/Time-series-prediction/examples/data/load_data.py", line 13, in <module>
    from data.read_data import PassengerData, SineData
  File "/content/Time-series-prediction/examples/data/read_data.py", line 13, in <module>
    from examples.feature.prepare_feature import transform2_lagged_feature,multi_step_y
ModuleNotFoundError: No module named 'examples.feature'
```

**My environment**: I am using a Google Colab instance, so you can [check my run here](https://colab.research.google.com/drive/1HY2kAa2i-JzJe896t5KO0pWyrZMRBywJ?usp=sharing). Feel free to add comments.

**Comment by LongxingTan** [comment]
@pnmartinez
Hey pnmartinez, 
I am not familar colab's running style, because we can't use it in China.

possible 1 solution is: you can try "cd examples" before running. Normally if I run it in termial without that, it can't find run_train.py also, so i'm not clear

possible 2 solution is: you can clone it again, i just modified it to relatively path import.

Hope it helps

**Comment by pnmartinez** [comment]
@LongxingTan absolutely fixed! Thank you so much.

Consider adding the linked notebook to the README, as it now works perfectly.
